### ISSUE TITLE
Create maintenance jobs in the app, as well as directly on the web interface

### ISSUE THREAD

**Issue by Jbithell** [bstudios/adam-rms#105]
Burrying it in the asset page isn't that helpful

**Comment by Jbithell** [comment]
> One idea I had that may come into this, I don't know, is something more like a yearly maintenance schedule. So that you could say every march we need to PAT test this item, or every April we need to check the movers lamp hours or whatever. I think it would make the job of the Equipment Manger's easier as the committees change so that people can see when regular maintenance needs doing.
> 
> The way it currently is, someone has to remember and log it into the RMS each year which as committees change things are going to get forgotten.

Could this be a CMS page?

**Comment by Robert-Watts** [comment]
I guess so but one thing that needs improving for that is internal links to assets.
