### ISSUE TITLE
Current page menu highlight does not work properly

### ISSUE THREAD

**Issue by Robert-Watts** [bstudios/adam-rms#109]
**Describe the bug**
The wrong pages are highlighted in the menu. Looks to be where the link is to #, and calls JS instead of navigating.

**To Reproduce**
1. Go to home page
2. Look at menu

**Expected behavior**
Dashboard should be highlighted.

![Screenshot_20210528-191343](https://user-images.githubusercontent.com/11817698/120026388-ea0df300-bfe9-11eb-8d26-fcb1af41f2a0.jpg)

**Comment by Jbithell** [comment]
Was a bug that crept into https://github.com/bstudios/adam-rms/commit/2a54b8049cb6e8b1c0ebd606560478069b96f819 - huge congratulations to @cherry-john on being the first contributor to have managed to get a bug into production 😛
