### ISSUE TITLE
File sharing to other links leads to 404.

### ISSUE THREAD

**Issue by chriscn** [bstudios/adam-rms#111]
**Describe the bug**
When accessing a file through a shared link, and then pressing Assets etc it leads to a 404. Originally discovered by @cherry-john and myself.

<img width="814" alt="Screenshot 2021-06-02 at 10 58 59" src="https://user-images.githubusercontent.com/25829276/120461505-f7cccb00-c391-11eb-9d39-9d5db05cd47c.png">

**Additional context**
The links are `https://inventory.yorktechsoc.org/file/assets.php` rather than `https://inventory.yorktechsoc.org/assets.php`. Should be a relatively easy fix. 

I would love to try and fix this issue but unsure where the code for inventory.techsoc.org is located.

**Comment by cherry-john** [comment]
I'll have a look at this whilst doing #60

**Comment by Jbithell** [comment]
@chriscn, sorry just as a tiny housekeeping thing - when investigating/working on an issue please assign it to yourself, to avoid others working on it as well simultaneously
