### ISSUE TITLE
[FEATURE] Assign asset types to projects

### ISSUE THREAD

**Issue by cherry-john** [bstudios/adam-rms#157]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When dispatching some assets the team would prefer to be able to dispatch any assets of a given asset type, rather than specific ones requested by the project manager. 
This is especially needed for cables, where it would take a long time to find a specific cable, when the team could just take the first 5 cables on the pile and add them to the project.

### Describe the solution you'd like

A way to add a specified number of assets to a project as an assignment, which is then replaced by individual assets at the dispatch stage.

### Describe alternatives you've considered

A simple text box so the Project manager can add asset type requests without adding the assets. This wouldn't keep track of how many assets have been assigned to a project though.

### Anything else?

Requested by Aidan Dixon

**Comment by Jbithell** [comment]
The challenge here (such a with your cable example) is differentiating between the different lengths of cable.

My original proposed solution to this (never implemented) was "subsitutions" where you could dispatch an asset substituting another of an identical type

**Comment by Jbithell** [comment]
> substituting another of an identical type

Example:

1. Cable of type "XLR 3 pin" is assigned to project by the PM. The asset assigned has a defined field of "Length (m)" which matches "10"
1. When scanning throuhg assets to dispatch them, another asset that has a defined field of "Length (m)" which matches "10" is scanned, but it is not assigned to the project.
1. The normal workflow here would be a popup saying "this asset is not assigned, would you like to assign it". The solution to this issue would be "an asset matching this asset is assigned, would you like to subsitute it?
1. This would mean same discounts & comments could be kept for the assignment, and just the asset swapped.

**Comment by cherry-john** [comment]
That would probably be significantly easier to implement
