### ISSUE TITLE
[BUG] Download on the App Store is low resolution.

### ISSUE THREAD

**Issue by chriscn** [bstudios/adam-rms#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1364" alt="Screenshot 2021-09-06 at 20 40 54" src="https://user-images.githubusercontent.com/25829276/132257340-8f04079b-e76f-45f7-a7d3-e6d9fcb4ff83.png">

### How are you accessing AdamRMS?

```markdown
- OS:
- Browser:
- Version:
```

**Comment by chriscn** [comment]
<img width="1680" alt="Screenshot 2021-09-06 at 21 10 53" src="https://user-images.githubusercontent.com/25829276/132258129-b5dd2160-4c07-4721-9efb-f63c523c5d6f.png">
Currenlty can't see any of the images locally. Once I fix this minor issue I can fix the real bug

**Comment by Jbithell** [comment]
Hi @chriscn, I've re-created the `png` from the `svg` provided by @apple (it was `120x40`) at a higher resoluiton (this will then get compressed again by the compression package in Docusaurus).

Thanks for your help in finding this, please could you review the PR?
