### ISSUE TITLE
Navigation issues in public site

### ISSUE THREAD

**Issue by Jbithell** [bstudios/adam-rms#60]
![image](https://user-images.githubusercontent.com/8408967/112054151-238b3380-8b4d-11eb-908a-bf32120ec113.png)
![image](https://user-images.githubusercontent.com/8408967/112054167-2a19ab00-8b4d-11eb-98db-68945baf1a61.png)

**Comment by Robert-Watts** [comment]
@cherry-john 
Was the herb crusted bake any good? (first screen shot)

**Comment by cherry-john** [comment]
> @cherry-john 
> 
> Was the herb crusted bake any good? (first screen shot)

Rob stop @ing me
