### ISSUE TITLE
Add project dates to the notification email of someone applying for a role

### ISSUE THREAD

**Issue by Jbithell** [bstudios/adam-rms#65]

**Comment by Jbithell** [comment]
@cherry-john can you remind me what the idea was here?

**Comment by cherry-john** [comment]
So when you have lots of events named the same thing (eg training) would be useful to have the full date/time info for the exact session

**Comment by Jbithell** [comment]
See for how I've interpreted it https://github.com/bstudios/adam-rms/commit/9b98f20cd4ac0562353f1680c8a028faa48dabe7 - let me know if you had something different in mind @cherry-john!
