### ISSUE TITLE
Manufacture page search doesn’t work

### ISSUE THREAD

**Issue by cherry-john** [bstudios/adam-rms#75]
**Describe the bug**
When searching for a manufacturer on the manufacturers page, the search box returns a blank page.

**To Reproduce**
1. Go to https://dash.adam-rms.com/manufacturers.php
2. Enter a name into the search box
3. See error (blank page)

**Expected behavior**
Manufacturer list sorted by search term.

**Screenshots**
![image](https://user-images.githubusercontent.com/54247748/117542204-95411300-b00f-11eb-9b1e-3800cf1f8d24.png)

**Smartphone (please complete the following information):**
 - Device: IPad Pro
 - OS: iOS 14.5.1
 - Browser: chrome, safari, firefox
 - Version: 87.0.4280.163/ ? /Firefox Daylight 33.1 (4629)

**Comment by Jbithell** [comment]
Thanks for the report @cherry-john!
