### ISSUE TITLE
Location file downloads do not work

### ISSUE THREAD

**Issue by Robert-Watts** [bstudios/adam-rms#76]
**Describe the bug**
Trying to download location files causes the following error to be displayed:

{"result":false,"error":{"message":"File not found"}}

Image thumbnails do work (meaning the file must have existed), however when you click to download the image the error above is produced.

**To Reproduce**
Trying to download any location file from the Joseph Round Tree location (https://dash.adam-rms.com/location/?files&id=5#).

**Screenshots**
![image](https://user-images.githubusercontent.com/11817698/117544930-895b4e00-b01b-11eb-9fe2-3e7536a9c1e0.png)

**Comment by Robert-Watts** [comment]
it seems to have fixed itself?

**Comment by Jbithell** [comment]
I think you might have been logged out at the time hence seeing those errors. 

Behaviour when logged out needs review

**Comment by Robert-Watts** [comment]
I _think_ what happened was there was a commit to the master branch while I was logged in, causing me to be logged out when the system was rebuilt. This meant that it caused errors when trying to download.

**Comment by Jbithell** [comment]
Essentially yes, although builds aren't generated on the server - the new container is just downloaded/installed then hotswapped. The sessions don't persist across the different containers so when that hot swap occurs everyone gets logged out (except in the app)
