### ISSUE TITLE
Outstanding/Assigned maintenance requests

### ISSUE THREAD

**Issue by nathanbillis** [bstudios/adam-rms#77]
**Is your feature request related to a problem? Please describe.**

- Would be nice to see outstanding maintenance requests, either as a list or a number on the Dashboard. That will quickly link directly to the maintenance page.

**Describe the solution you'd like**

- An addition of widget/business stat for the dash with outstanding maintenance requests, and another one with assigned to me that links to the maintenance page. 

**Describe alternatives you've considered**

- Not having the feature; having a combined widget, with the number of outstanding maintenance request and number assigned to "me"; or having two separate ones with the separate stats.

**Additional context**
Widget would sit on this page:
[![Image from Gyazo](https://i.gyazo.com/b812dad6742d7ed08532e3af904ce32e.png)](https://gyazo.com/b812dad6742d7ed08532e3af904ce32e)

**Comment by Jbithell** [comment]
Slightly hijacking this issue to acutally achieve something else as well in https://github.com/bstudios/adam-rms/pull/80
