### ISSUE TITLE
Error when trying to delete show recruitment

### ISSUE THREAD

**Issue by cherry-john** [bstudios/adam-rms#78]
**Describe the bug**
When deleting an advertised role for an event, an error of "Sorry we couldn't complete this action - please try again! No project for action" is shown

**To Reproduce**
1. Go to https://dash.adam-rms.com/project/crew/vacantCrew.php?id=140
2. Delete a show role (eg "Setup/Packdown Crew")
3. See error

**Expected behavior**
Advertised role to disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/54247748/117575639-94c17e80-b0da-11eb-97fa-6e1f2980f5ac.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox, Chrome
 - Version 88.0.1, 90.0.4430.93

**Comment by Jbithell** [comment]
Great spot thanks very much!
