### ISSUE TITLE
Cannot view assets

### ISSUE THREAD

**Issue by Robert-Watts** [bstudios/adam-rms#82]
**Describe the bug**
An Internal Server error is produced when trying to look at any asset. HTTP 500.

**To Reproduce**
1. Login
3. Go to any asset e.g. [https://dash.adam-rms.com/asset.php?id=404]( https://dash.adam-rms.com/asset.php?id=404)
4. Get a fun HTTP 500 error instead of the asset I requested

**Expected behavior**
The asset I requested

**Screenshots**
![image](https://user-images.githubusercontent.com/11817698/117658578-ceee5700-b192-11eb-9f15-80e61d3ed082.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 90

**Additional context**
The training manager got this error too

**Comment by Jbithell** [comment]
Status page updated https://github.com/bstudios/statusfy-status/commit/f71441aae2afe16caf0be9cbb2b3f4634beb6388
