### ISSUE TITLE
Public Site Documentation

### ISSUE THREAD

**Issue by Robert-Watts** [bstudios/adam-rms#94]
**Is your feature request related to a problem? Please describe.**
There is no instructions on how to setup the public site.

**Describe the solution you'd like**
A guide on how to set up the public site in a local development environment.

**Comment by Jbithell** [comment]
As discussed with Rob, the current workaround is to set `instances_publicConfig` to 


```json
{"enabled":true,"enableAssets":true,"enableAssetAvailability":true,"enableAssetDescriptions":true,"enableAssetNotes":true,"enableVacancies":true,"footerText":"","headerImage":null,"homepageHTML":"","customDomains":["localhost"]}
```
