### ISSUE TITLE
Files Missing

### ISSUE THREAD

**Issue by Jbithell** [bstudios/adam-rms#98]
Something funky is going on with files, with different users seeing different files listed.

@Robert-Watts saw:
![image](https://user-images.githubusercontent.com/8408967/119796969-ba6bc780-bed1-11eb-83b5-0479081aae04.png)

@jbithell saw:
![image](https://user-images.githubusercontent.com/8408967/119796996-c192d580-bed1-11eb-95c4-faaaf5814893.png)

On the same asset!

**Comment by Jbithell** [comment]
After a bit of investigation this turned out to be user error, @Robert-Watts and I were looking at different assets

**Comment by Robert-Watts** [comment]
Sorry my bad 😀
